
INSERT INTO candidat (Nom, Prenom) VALUES ('AUDOIN', 'Laurent');
INSERT INTO candidat (Nom, Prenom) VALUES ('BARBAY', 'Elisabeth');
INSERT INTO candidat (Nom, Prenom) VALUES ('BARNIER', 'Michel');
INSERT INTO candidat (Nom, Prenom) VALUES ('BERNARD', 'Charles-Henri');
INSERT INTO candidat (Nom, Prenom) VALUES ('BLISKO', 'Serge');
INSERT INTO candidat (Nom, Prenom) VALUES ('BLOT', 'Yvan');
INSERT INTO candidat (Nom, Prenom) VALUES ('BROSSAT', 'Ian');
INSERT INTO candidat (Nom, Prenom) VALUES ('CASTANY', 'Françoise');
INSERT INTO candidat (Nom, Prenom) VALUES ('CHAIBI', 'Leïla');
INSERT INTO candidat (Nom, Prenom) VALUES ('CHEVALIER', 'Emile');
INSERT INTO candidat (Nom, Prenom) VALUES ('COHN BENDIT', 'Daniel');
INSERT INTO candidat (Nom, Prenom) VALUES ('COSSERON DE VILLENOISY', 'Patrick');
INSERT INTO candidat (Nom, Prenom) VALUES ('COTTET', 'Chantal');
INSERT INTO candidat (Nom, Prenom) VALUES ('CUSA', 'Miron');
INSERT INTO candidat (Nom, Prenom) VALUES ('DARMANGEAT', 'Christophe');
INSERT INTO candidat (Nom, Prenom) VALUES ('DAYMARD', 'Jean-Pierre');
INSERT INTO candidat (Nom, Prenom) VALUES ('DE BOER', 'Axel');
INSERT INTO candidat (Nom, Prenom) VALUES ('DE SARNEZ', 'Marielle');
INSERT INTO candidat (Nom, Prenom) VALUES ('DEBAH', 'Farid');
INSERT INTO candidat (Nom, Prenom) VALUES ('DECOLLOGNE', 'Michel');
INSERT INTO candidat (Nom, Prenom) VALUES ('DEFLANDRE', 'Clément');
INSERT INTO candidat (Nom, Prenom) VALUES ('DELANOË', 'Gaspard');
INSERT INTO candidat (Nom, Prenom) VALUES ('DESIR', 'Harlem');
INSERT INTO candidat (Nom, Prenom) VALUES ('DI RUZZA', 'Antoinette');
INSERT INTO candidat (Nom, Prenom) VALUES ('DU ROSCOAT', 'Annick');
INSERT INTO candidat (Nom, Prenom) VALUES ('DUBOIS', 'Jean-Michel');
INSERT INTO candidat (Nom, Prenom) VALUES ('DUCQ', 'Alain');
INSERT INTO candidat (Nom, Prenom) VALUES ('EL KHOURY', 'Claudine');
INSERT INTO candidat (Nom, Prenom) VALUES ('ENJALBERT', 'Jean-Pierre');
INSERT INTO candidat (Nom, Prenom) VALUES ('FIZE', 'Michel');
INSERT INTO candidat (Nom, Prenom) VALUES ('FOUIX', 'Elisabeth');
INSERT INTO candidat (Nom, Prenom) VALUES ('GHEHIOUECHE', 'Farid');
INSERT INTO candidat (Nom, Prenom) VALUES ('GOUJON', 'Philippe');
INSERT INTO candidat (Nom, Prenom) VALUES ('GOVERNATORI', 'Jean-Marc');
INSERT INTO candidat (Nom, Prenom) VALUES ('HEROLD', 'Sabine');
INSERT INTO candidat (Nom, Prenom) VALUES ('HUCHON', 'Jean-Paul');
INSERT INTO candidat (Nom, Prenom) VALUES ('JACONO', 'Isabelle');
INSERT INTO candidat (Nom, Prenom) VALUES ('JACOT', 'Jean-Marc');
INSERT INTO candidat (Nom, Prenom) VALUES ('JASIUKIEWICZ', 'Mario');
INSERT INTO candidat (Nom, Prenom) VALUES ('JOURNIAC', 'Marianne');
INSERT INTO candidat (Nom, Prenom) VALUES ('JULIA', 'Jean-Marie');
INSERT INTO candidat (Nom, Prenom) VALUES ('KAHN', 'Axel');
INSERT INTO candidat (Nom, Prenom) VALUES ('LANCE', 'Guillaume');
INSERT INTO candidat (Nom, Prenom) VALUES ('LANGLOIS', 'Patrice');
INSERT INTO candidat (Nom, Prenom) VALUES ('LATOUR', 'Jean-François');
INSERT INTO candidat (Nom, Prenom) VALUES ('LE HYARIC', 'Patrick');
INSERT INTO candidat (Nom, Prenom) VALUES ('LECOQ', 'Jean-Pierre');
INSERT INTO candidat (Nom, Prenom) VALUES ('LOCUSSOL', 'André');
INSERT INTO candidat (Nom, Prenom) VALUES ('MANSOUR', 'Mustapha');
INSERT INTO candidat (Nom, Prenom) VALUES ('MARIETTE', 'Clara');
INSERT INTO candidat (Nom, Prenom) VALUES ('MARTINS', 'Jean-François');
INSERT INTO candidat (Nom, Prenom) VALUES ('MBALA MBALA', 'Dieudonné');
INSERT INTO candidat (Nom, Prenom) VALUES ('MERCIER', 'Jean-Pierre');
INSERT INTO candidat (Nom, Prenom) VALUES ('MEYRUEY', 'Benoit');
INSERT INTO candidat (Nom, Prenom) VALUES ('MIGNOT', 'Alfred');
INSERT INTO candidat (Nom, Prenom) VALUES ('MOISAN DE KERBINO', 'Gilles');
INSERT INTO candidat (Nom, Prenom) VALUES ('MOURGUY', 'Alain');
INSERT INTO candidat (Nom, Prenom) VALUES ('NAVARRE', 'Philippe');
INSERT INTO candidat (Nom, Prenom) VALUES ('NEROUD', 'Thérèse');
INSERT INTO candidat (Nom, Prenom) VALUES ('PARISOT', 'Jacques');
INSERT INTO candidat (Nom, Prenom) VALUES ('PASQUINET', 'Jean-Luc');
INSERT INTO candidat (Nom, Prenom) VALUES ('PECRESSE', 'Valérie');
INSERT INTO candidat (Nom, Prenom) VALUES ('PEJO', 'Philippe');
INSERT INTO candidat (Nom, Prenom) VALUES ('PERLICAN', 'Rolande');
INSERT INTO candidat (Nom, Prenom) VALUES ('PERUCCA', 'Maxime-Louis');
INSERT INTO candidat (Nom, Prenom) VALUES ('RAISON', 'Monique');
INSERT INTO candidat (Nom, Prenom) VALUES ('RANKE-CORMIER', 'Marianne');
INSERT INTO candidat (Nom, Prenom) VALUES ('REBOT', 'Stella');
INSERT INTO candidat (Nom, Prenom) VALUES ('RIVIERE', 'Jérôme');
INSERT INTO candidat (Nom, Prenom) VALUES ('SALVISBERG', 'Catherine');
INSERT INTO candidat (Nom, Prenom) VALUES ('SLAOUTI', 'Omar');
INSERT INTO candidat (Nom, Prenom) VALUES ('SOUCHET', 'Jacques');
INSERT INTO candidat (Nom, Prenom) VALUES ('SOULA', 'Leila');
INSERT INTO candidat (Nom, Prenom) VALUES ('TIEU', 'Chenva');
INSERT INTO candidat (Nom, Prenom) VALUES ('TOUHAMI', 'Majid');
INSERT INTO candidat (Nom, Prenom) VALUES ('TRAORE', 'Lassina');
INSERT INTO candidat (Nom, Prenom) VALUES ('TRIDON', 'Sylvie');
INSERT INTO candidat (Nom, Prenom) VALUES ('VASSEUR', 'Véronique');
INSERT INTO candidat (Nom, Prenom) VALUES ('VIANO', 'Lucie');
INSERT INTO candidat (Nom, Prenom) VALUES ('VINCIGUERRA', 'Laurent');

